<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="API_AutoFramework"
           tests="12"
           failures="6"
           errors="0"
           skipped="0"
           time="7.292">
    <properties></properties>

            <testcase
                name="login"
                time="0.937"
                classname="com.qa.API_F02.tests.TestCase_001_CG">

            <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
                <![CDATA[java.lang.AssertionError: expected [200] but found [400]
                org.testng.Assert.fail(Assert.java:99)org.testng.Assert.failNotEquals(Assert.java:1037)org.testng.Assert.assertEqualsImpl(Assert.java:140)org.testng.Assert.assertEquals(Assert.java:122)org.testng.Assert.assertEquals(Assert.java:907)org.testng.Assert.assertEquals(Assert.java:917)com.qa.API_F02.tests.TestCase_001_CG.login(TestCase_001_CG.java:73)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </failure>
    </testcase>
            <testcase
                name="login"
                time="0.592"
                classname="com.qa.API_F02.tests.TestCase_001_CG">

            <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
                <![CDATA[java.lang.AssertionError: expected [200] but found [400]
                org.testng.Assert.fail(Assert.java:99)org.testng.Assert.failNotEquals(Assert.java:1037)org.testng.Assert.assertEqualsImpl(Assert.java:140)org.testng.Assert.assertEquals(Assert.java:122)org.testng.Assert.assertEquals(Assert.java:907)org.testng.Assert.assertEquals(Assert.java:917)com.qa.API_F02.tests.TestCase_001_CG.login(TestCase_001_CG.java:73)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </failure>
    </testcase>
            <testcase
                name="login"
                time="0.599"
                classname="com.qa.API_F02.tests.TestCase_001_CG">

            <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
                <![CDATA[java.lang.AssertionError: expected [200] but found [400]
                org.testng.Assert.fail(Assert.java:99)org.testng.Assert.failNotEquals(Assert.java:1037)org.testng.Assert.assertEqualsImpl(Assert.java:140)org.testng.Assert.assertEquals(Assert.java:122)org.testng.Assert.assertEquals(Assert.java:907)org.testng.Assert.assertEquals(Assert.java:917)com.qa.API_F02.tests.TestCase_001_CG.login(TestCase_001_CG.java:73)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </failure>
    </testcase>
            <testcase
                name="deleteApi"
                time="0.100"
                classname="com.qa.API_F02.tests.TestCase_001_CG">

            <failure type="org.apache.http.client.ClientProtocolException" message="(null)">
                <![CDATA[org.apache.http.client.ClientProtocolException
                org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)com.qa.API_F02.restclient.RestClient_getPostPutDelete_CG.delete(RestClient_getPostPutDelete_CG.java:140)com.qa.API_F02.tests.TestCase_001_CG.deleteApi(TestCase_001_CG.java:87)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
                    Caused by: org.apache.http.ProtocolException: Target host is not specified
                    org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)com.qa.API_F02.restclient.RestClient_getPostPutDelete_CG.delete(RestClient_getPostPutDelete_CG.java:140)com.qa.API_F02.tests.TestCase_001_CG.deleteApi(TestCase_001_CG.java:87)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
                ]]>
            </failure>
    </testcase>
            <testcase
                name="login"
                time="0.848"
                classname="com.qa.API_F02.tests.TestCase_001_CG">

            <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
                <![CDATA[java.lang.AssertionError: expected [200] but found [400]
                org.testng.Assert.fail(Assert.java:99)org.testng.Assert.failNotEquals(Assert.java:1037)org.testng.Assert.assertEqualsImpl(Assert.java:140)org.testng.Assert.assertEquals(Assert.java:122)org.testng.Assert.assertEquals(Assert.java:907)org.testng.Assert.assertEquals(Assert.java:917)com.qa.API_F02.tests.TestCase_001_CG.login(TestCase_001_CG.java:73)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </failure>
    </testcase>
            <testcase
                name="login"
                time="0.569"
                classname="com.qa.API_F02.tests.TestCase_001_CG">

            <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
                <![CDATA[java.lang.AssertionError: expected [200] but found [400]
                org.testng.Assert.fail(Assert.java:99)org.testng.Assert.failNotEquals(Assert.java:1037)org.testng.Assert.assertEqualsImpl(Assert.java:140)org.testng.Assert.assertEquals(Assert.java:122)org.testng.Assert.assertEquals(Assert.java:907)org.testng.Assert.assertEquals(Assert.java:917)com.qa.API_F02.tests.TestCase_001_CG.login(TestCase_001_CG.java:73)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </failure>
    </testcase>


            <testcase
                name="login"
                time="0.720"
                classname="com.qa.API_F02.tests.TestCase_001_CG">
            </testcase>
            <testcase
                name="login"
                time="0.598"
                classname="com.qa.API_F02.tests.TestCase_001_CG">
            </testcase>
            <testcase
                name="login"
                time="0.613"
                classname="com.qa.API_F02.tests.TestCase_001_CG">
            </testcase>
            <testcase
                name="login"
                time="0.673"
                classname="com.qa.API_F02.tests.TestCase_001_CG">
            </testcase>
            <testcase
                name="login"
                time="0.623"
                classname="com.qa.API_F02.tests.TestCase_001_CG">
            </testcase>
            <testcase
                name="getApi"
                time="0.420"
                classname="com.qa.API_F02.tests.TestCase_001_CG">
            </testcase>
</testsuite>
